### ISSUE TITLE
Project will not build, issue with GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by CZHach** [bimsina/NotHotDog#1]
Hi, this sounds like a really cool repo to play around with. But I'm having trouble getting it to build.

I upgraded my versions of Android Studio, AndroidSDK, JDK, and flutter.

I also ran 'flutter doctor' and get no issues found.

Additionally, I ran 'flutter packages get' to make sure I had everything needed.

But when I try to use 'flutter run' to run the app, I get the following error:

> e: G:\Code Projects and Solutions\Flutter\NotHotDog-master\android\app\src\main\kotlin\com\bimsina\nothotdog\MainActivity.kt: (6, 27): Unresolved reference: GeneratedPluginRegistrant
> e: G:\Code Projects and Solutions\Flutter\NotHotDog-master\android\app\src\main\kotlin\com\bimsina\nothotdog\MainActivity.kt: (11, 5): Unresolved reference: GeneratedPluginRegistrant

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
When I navigate to the file with the errors, I see this:

```
package com.bimsina.nothotdog

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```
I'm pretty new with Flutter, so I'm not exactly sure what to do next. I've Googled it a ton, but can't really find anything specific.

Honestly I'm not sure if this is even a Flutter issue or an issue with java.

Has anyone ever seen anything like this before?

Thanks!

**Comment by bimsina** [comment]
Did you add google-services.json?

**Comment by debasmitabounce** [comment]
Any update? I also got the issue

**Comment by bimsina** [comment]
I have fixed the issue by recreating the project. It should work fine now.
